<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RATINGS [
    <!ELEMENT RATINGS (CD*)>
    <!ELEMENT CD (ARTIST, ALBUM, NOTE)>
    <!ELEMENT ARTIST (#PCDATA)>
    <!ELEMENT ALBUM (#PCDATA)>
    <!ELEMENT NOTE (#PCDATA)>

    <!ATTLIST CD
        id ID #IMPLIED
    >
]>


<RATINGS>
<CD>
<ARTIST>DANO</ARTIST>
<ALBUM>EHHPDSR</ALBUM>
<NOTE>9,25</NOTE>
</CD>
<CD>
<ARTIST>Hoke</ARTIST>
<ALBUM>BBO</ALBUM>
<NOTE>9</NOTE>
</CD>
<CD>
<ARTIST>MDA</ARTIST>
<ALBUM>RS4</ALBUM>

<NOTE>8,5</NOTE>
</CD>
<CD>
<ARTIST>Elio Toffana</ARTIST>
<ALBUM>Shock Wave</ALBUM>
<NOTE>8,75</NOTE>
</CD>
<CD>
<ARTIST>Ergo Pro</ARTIST>
<ALBUM>Opera Fidelio</ALBUM>
<NOTE>8,5</NOTE>
</CD>
<CD>
<ARTIST>Mar√≠a Escarmiento</ARTIST>
<ALBUM>Witch things</ALBUM>
<NOTE>8</NOTE>
</CD>
<CD>
<ARTIST>Gloosito</ARTIST>
<ALBUM>Global</ALBUM>
<NOTE>7,75</NOTE>
</CD>
<CD>
<ARTIST>Saske</ARTIST>
<ALBUM>BAR$</ALBUM>
<NOTE>7,5</NOTE>
</CD>
<CD>
<ARTIST>El Virtual</ARTIST>
<ALBUM>THE 3 Pt.II: THE WAY</ALBUM>
<NOTE>8,25</NOTE>
</CD>
</RATINGS>



